name: GLCoins-Server
version: '1.0-SNAPSHOT'
main: com.deadshotmdf.gLCoins_Server.GLCoinsS
api-version: '1.21'
authors: [ DeadshotMDF ]
depend:
  - Vault
  - Essentials
loadbefore:
  - GLCBank
libraries:
  - com.zaxxer:HikariCP:6.0.0
  - mysql:mysql-connector-java:8.0.13
commands:
  shit:
