name: GLCoins-Server
version: '1.0-SNAPSHOT'
main: com.deadshotmdf.gLCoins_Server.GLCoinsS
api-version: '1.21'
authors: [ DeadshotMDF ]
libraries:
  - com.zaxxer:HikariCP:6.0.0
  - org.postgresql:postgresql:42.7.3
commands:
  shit:
